language: android

jdk: oraclejdk8

script: "./gradlew build"

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # Additional components
    #- extra-google-google_play_services
    #- addon-google_apis-google-19

    # Specify at least one system image, if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA7_HOME